language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v12
  - v10
before_install:
  - npm install -g coveralls @patrickhulce/scripts nyc
script:
  - npm run start
  - npm run test:lint
  - nyc npm run test:unit
after_success:
  - nyc report --reporter=lcov | coveralls || echo 'Failed to upload to coveralls...'
  - hulk npm-publish --yes
